# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_poll_pollplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
